services:
  app:
    build:
      context: .
      target: production
#    platform: linux/amd64
    depends_on:
      - db
    init: true
    networks:
      default:
        aliases:
          - app.test
    volumes:
      - ./:/opt/app
    ports:
      - 3000:3000
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    image: postgres:12.2
    networks:
      default:
        aliases:
          - db.test
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/build:rw

volumes:
  postgres_data: { }

version: '3.8'
