# Canonical docker-compose configuration
services:
  app:
    build:
      context: .
      target: production
    depends_on:
      - db
    init: true
    restart: always

  db:
    image: postgres:12.2
    networks:
      default:
        aliases:
          - db.test
    restart: always

version: '3.8'
