# Development docker-compose configuration, overlaid by default
# - see https://docs.docker.com/compose/extends/
services:
  app:
#    platform: linux/amd64
    networks:
      default:
        aliases:
          - app.test
    volumes:
      - ./:/opt/app
    ports:
      - 3000:3000

  db:
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    networks:
      default:
        aliases:
          - db.test
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/build:rw

volumes:
  postgres_data: { }
