---

development:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/galc-dev?pool=5' %>

test:
  url: <%= ENV['DATABASE_URL'] ||'postgres://root:root@db/galc-test?pool=5' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/galc-prod' %>
