name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: docker-compose build --pull

      - name: up
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: test
        # disable TTY: workaround for https://github.com/actions/runner/issues/241
        run: docker-compose exec -T -e RAILS_ENV=test app rake -t

      - name: collect Docker logs
        if: ${{ always() }}
        run: docker-compose logs | tee artifacts/docker-compose.log

      - name: copy artifacts from container
        if: ${{ always() }}
        run: docker cp galc-api-app-1:/opt/app/artifacts/. artifacts

      - name: upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/**

      - name: down
        if: ${{ always() }}
        run: docker-compose down --remove-orphans
  publish:
    runs-on: ubuntu-latest
    needs: build
#    if: github.ref_name == 'release'
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
