name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          # TODO: run job in a container so we don't need to expose ports
          - 5432:5432

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # TODO: build and push image first, then pull it to run this whole job in a container
      #       (simplifies Docker networking & host naming)

      - name: build
        run: docker build . -t galc-api:ci

      - name: test
        run: |
          docker run \
                     --network host \
                     -u root \
                     -v artifacts:/opt/app/artifacts \
                     -e RAILS_ENV=test \
                     -e DATABASE_URL='postgres://root:root@127.0.0.1:5432/galc-test?pool=5' \
                     galc-api:ci \
                     bundle exec rake -t

      - name: rubocop
        run: |
          docker run -u root \
                     -v artifacts:/opt/app/artifacts \
                     galc-api:ci \
                     bundle exec rubocop

      - name: upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/**

      - name: build
        run: docker build .

  publish:
    runs-on: ubuntu-latest
    needs: build
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
