name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: docker-compose build --pull

      - name: up
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: test
        # disable TTY: workaround for https://github.com/actions/runner/issues/241
        run: docker-compose exec -T -e RAILS_ENV=test app rake -t

      - name: collect Docker logs
        if: ${{ always() }}
        run: docker-compose logs | tee artifacts/docker-compose.log

      - name: copy artifacts from container
        if: ${{ always() }}
        run: docker-compose cp app:/opt/app/artifacts/. artifacts

      - name: upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/**

      - name: down
        if: ${{ always() }}
        run: docker-compose down --remove-orphans
