name: Build
on: [ push, pull_request, release, workflow_dispatch ]
env:
  REGISTRY: ghcr.io
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # See https://github.com/docker/build-push-action/blob/v2.10.0/TROUBLESHOOTING.md#repository-name-must-be-lowercase
      - name: Sanitize image name
        uses: actions/github-script@v6
        id: image-name
        with:
          result-encoding: string
          script: return '${{ env.REGISTRY }}/${{ github.repository }}'.toLowerCase()

      - name: Get short SHA
        run: |
          echo SHORT_SHA="${GITHUB_SHA:0:7}" >> $GITHUB_ENV

    outputs:
      base_image_name: ${{ steps.image-name.outputs.result }}
      build_image: ${{ steps.image-name.outputs.result }}:${{ env.SHORT_SHA }}

  build:
    if: github.event_name != 'release'
    needs: setup
    env:
      BUILD_IMAGE: ${{ needs.setup.outputs.build_image }}

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.BUILD_IMAGE }}

    outputs:
      build_image: ${{ env.BUILD_IMAGE }}

  test:
    if: github.event_name != 'release'
    needs: build

    runs-on: ubuntu-latest

    container:
      image:  ${{ needs.build.outputs.build_image }}

    defaults:
      run:
        working-directory: /opt/app

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root

    steps:
      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rake check -t

      - name: Run style checks
        run: bundle exec rubocop

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: /opt/app/artifacts/**

  # TODO: DRY push and push-release
  push:
    if: github.event_name != 'release'

    needs: [ setup, build, test ]
    env:
      BASE_IMAGE_NAME: ${{ needs.setup.outputs.base_image_name }}
      BUILD_IMAGE: ${{ needs.build.outputs.build_image }}

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.BASE_IMAGE_NAME }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ env.BUILD_IMAGE }}
          dst: |
            ${{ steps.meta.outputs.tags }}

  # TODO: DRY push and push-release
  push-release:
    if: github.event_name == 'release' && github.event.action == 'published'

    needs: [setup]
    env:
      BASE_IMAGE_NAME: ${{ needs.setup.outputs.base_image_name }}
      BUILD_IMAGE: ${{ needs.setup.outputs.build_image }}

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.BASE_IMAGE_NAME }}
          tags:
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ env.BUILD_IMAGE }}
          dst: |
            ${{ steps.meta.outputs.tags }}
